name: Upload to Archive.org
on: push

jobs:
  job:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            
      - name: Create bundle
        run: git bundle create amog-cli.bundle --all

      - name: Upload file to archive.org
        uses: palewire/internet-archive-upload@v1
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          identifier: amog-cli-${{ github.sha }}
          files: amog-cli.bundle